name: brainscan
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pillow
  - plotly
  - pyyaml
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - umap-learn
  - pip:
      - opencv-python-headless
